### ISSUE TITLE
[Snippets] Add Markdown style formatting to snippets

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1028]
It would be nice to have formatting abilities for snippets (bold, bullets, etc).

**Comment by jstanden** [comment]
You can already use Markdown in snippets, since it's supposed to be readable as plaintext.

However, there isn't a flag on snippets that they include formatting, which could be used to enable formatting in a message/comment when the snippet is pasted.

A good way around that is to use the 'draft generator' widget on ticket profiles as the basis for smarter snippets. When programmatically creating drafts, you can enable formatting, set the body, and any other compose/reply fields (custom fields, subject, recipients, owner, status).

**Comment by beatbesmer** [comment]
We could close this or move it to "nice to have": There are _simple_ workers (windows user) which try to avoid the _console- way_ of adding markdown syntax manually :) They just asked for such a toolbar similar to the compose/reply dialog. But we can try to teach them markdown

**Comment by jstanden** [comment]
This could be done with interactions in the reply editor now.
