### ISSUE TITLE
#signature not replaced in "Send email to recipients"- action

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1055]
Steps to reproduce:

Behavior of type: **Record custom behavior on ticket**
Action: **Send email to recipients**
Insert "#signature" in Content and send the e-mail

The e-mail ist sent properly, but the #signature placeholder won't be replaced and remains visible

Tested with Cerb 9.3.8

**Comment by jstanden** [comment]
Hi Beat! I believe the underlying issue here won't exist in 9.4+ due to a refactor that moved the `#command` functionality into the compose/reply code.

There were many improvements related to drafts and scheduled replies where we want to keep a placeholder like `#signature` for as long as possible, because you can convert a scheduled message back to an editable draft until the last minute. You can also include the sig placeholder in broadcasts now, etc.

The main issue with your example is that the bot is sending the message rather than a worker. In 9.4, signature records can have plaintext and HTML variations. It almost seems like they need worker and non-worker (bot/system) variations as well.

Another option would be the groups/buckets configuring a different signature for workers or automated replies. The latter wouldn't have worker placeholders.

**Comment by beatbesmer** [comment]
> The main issue with your example is that the bot is sending the message rather than a worker.

Makes sense. Thank you.

I've already a workaround in mind. Based on your suggestion for a localized signature (search and replace before sending) which requires a signature made of several own placeholders. I'll see if this will be an "economic" solution. 

However, i'm looking forward to 9.4 with all new improvements

**Comment by beatbesmer** [comment]
A working (temporary) solution is to use a worker- variable on the **Record custom behavior on ticket** and an to exclude this value in the **Send email to recipients** if it isn't set. Sure, I've to rebuild the whole signature what looses dependency to changes at the original bucket / group- signature.

**Comment by jstanden** [comment]
This can be done better with automations now.
