### ISSUE TITLE
[Bot] "Replace text in message content" doesn't replace string located in a signature

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1148]
Behavior: _Before message sent by worker_
Action: _Replace text in message content_

This action seems not replace a string set in the signature. If the string occures in the mail- body, it will be replaced as expected. Affects plaintext and HTML signatures / mails

This worked in recent versions

**Comment by jstanden** [comment]
The order of operations here changed, because 'Before message sent by worker' can now modify the body (including `#commands`), override the 'send at' time, etc.

What's the use case for changing the signature? Perhaps we can tackle that another way.

**Comment by beatbesmer** [comment]
A localized signature, where the language is taken from a CF in the ticket. See HAN-29598-915.

**Comment by beatbesmer** [comment]
If we could **manually select a signature** for a concrete message trough the **before message sent by worker** behavior, this could also be a solution.
So we'd just have to create a signature for each language. Not very efficient if there are multiple type of signatures (compared to the "replace"- solution), but could be a workaround..

**Comment by jstanden** [comment]
This functionality was just refactored in 9.6. I'll give it another look.

**Comment by jstanden** [comment]
This now works as expected in the upcoming 9.6 update. The `#signature` is substituted *before* the "Before message sent" event triggers.

**Comment by beatbesmer** [comment]
I'm using 2020081701 and the behavior seems unchanged: **Before message sent by worker** replaces only strings which are visible within the compose/reply form, but not those inserted by the #signature.

**Comment by jstanden** [comment]
Yeah, there was a change during 9.6 development due to needing separate plaintext and HTML signatures for the same message.

Prior to 9.6 we were converting the HTML part back to text. Now we keep the raw Markdown as the text/plain, and it generates the text/html part.

In the compose/reply code, there's only the Markdown content until the message is actually sent, so we needed to generate the signatures early, store them, then replace `#signature` with the appropriate format (text/html) once we had separate parts.

So **Before message sent by worker** will only see `#signature`. Perhaps we can expose the text/HTML signature content to the behavior separately. Changes to those would still be replaced at the end.

**Comment by jstanden** [comment]
In 10.3, this use case can be solved using the new `cerb_automation()` function in scripting.
