### ISSUE TITLE
New comments, focus is briefly on the [x] close button

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1165]
If you're too quick on commenting, a space can close the comment window because of where focus starts.

Jeff also noted:
> I've seen that when creating tasks via library on a project board

**Comment by jstanden** [comment]
This was more involved than expected.

The focus comes from jQuery UI itself. We need an `autofocus` element in the body of the popup before the Ajax comes back. That has to be something focusable (e.g. link/button/textinput), and it can't be hidden because it would lose focus.

If we just unfocus the close button, keystrokes go to the page, which could trigger unintended actions (e.g. ticket profile page closing a ticket on `c`).

Because comments focus the textarea, and it has to enhance to an Ace editor which has a small delay. It's still possible to lose the old popup body focus while that happens.

Essentially, we're going to have to focus on some off-screen element and block keystrokes. Something outside of the popup so it's consistent during Ajax. Then focus in the code editor when ready.

I'll likely add a reusable "keyboard sandbox" element to the platform for situations like this.

**Comment by jstanden** [comment]
I haven't heard this one come up again. I'm going to close it out, and we can revive if needed.
