### ISSUE TITLE
[Search/Records/UX] Search Auto-Complete is too aggressive

### ISSUE THREAD

**Issue by DavidAllewell** [jstanden/cerb#1228]
We're seeing in 9.4.13 a very aggressive attempt to auto-complete filters/functions within the Cerb search box, going so far as to be almost unusable until you type enough to avoid a match entirely.

I've included a screenshot below of myself searching for "Dave" within a snippets list. As you can see, the auto-complete finds the letters [d], [a], [v], and [e] in order, but not consecutively, so attempts to auto-complete the filter. This means that searching for the term "Dave" requires me to actively dismiss the auto-complete prompts before hitting Enter:

![Screenshot 2020-02-24 at 15 11 26](https://user-images.githubusercontent.com/17696511/75164122-32b86b80-5718-11ea-84ae-7cebb1c0acf2.png)

**Comment by jstanden** [comment]
Hi David! This is expected behavior, but we can make it more configurable.

The filterless full-text searches are deprecated. If possible, always use a filter like `firstName:` to remove any ambiguity.

If you're often doing full-text searches, you can set up a workspace with dashboard filters:
https://cerb.ai/guides/dashboards/filters/

That's more user-friendly than the full query syntax.

**Comment by DavidAllewell** [comment]
Hey @jstanden, noted on the deprecation warning, thanks!

The real criticism I have here is the auto-selection of the filters in the dropdown. I'll type a full query, be ready to search for it, but the last thing I'll have typed will have matched another filter, so it will auto-fill the filter and force me to delete everything that was added.

Personally, I'd find an "opt in" to the auto-fill selection being preferable, requiring user-action to select any of the filters.

**Comment by the4ndy** [comment]
the biggest problem is that it auto fills with the space key. Auto fill with tab not with space or any other key.

Also, im not a fan of "its expected behvior", no other search engine will give you results for wildly non consecutive characters in a result

**Comment by jstanden** [comment]
@the4ndy Hey!

Can you provide an example where the search query is autocompleting on space? I do see the issue if you're trying to search for a single term that happens to match a filter, like 'org'. When you hit enter, it assumes you're accepting the autocompletion rather than doing a fulltext search.

As for matching the non-consecutive characters, the queries act more like an IDE than a search engine. There's a grammar for queries. So something like `linadd` is shorthand for `links.address:`.

We're currently relying on Ace Editor for that autocompletion functionality. We use the token tree for contextual autocompletion (e.g. record and type specific suggestions in deeply nested filters).

With Ace, when you disable 'exact matches' to get case-insensitive partial matches, it always enables the fuzzy matching.

It's likely we'll just implement our own autocompletion for queries, the way we currently do on compose/reply with the `#commands`. That would give us full control to provide a much better UX.

**Comment by jstanden** [comment]
This is fixed for 9.5.5. The first match in the suggestions menu is no longer automatically selected. You can down-arrow to make a selection. Pressing `<RETURN>` without making a selection will close the menu.

![2020-04-25 15-53-22 2020-04-25 15_54_31](https://user-images.githubusercontent.com/63288/80292700-18e1d780-870d-11ea-8649-370801e365ce.gif)
