### ISSUE TITLE
[Mail/Conversation] Wrong date in header leads to confusing arrangement in conversation

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1259]
I assume that a sender has misconfigured the local time of his computer so that the mail header has used an incorrect `date` . Because Cerb arranges messages in the conversation history by their `date`, users were confused that the ticket was changed 7 hours ago, but no message in the history shows up that was added 7 hours ago.

We had a similar issue a few months ago. This happens really rarely.

The message with the following header was arranged at the **older** end in the history..

```
Received: ******************3
	by ****************3 (Postfix) with ESMTPSA id *************
	for <*********************>; Mon,  6 Apr 2020 00:43:49 +0200 (CEST)
From: ************* <****************3@***************>
Content-Type: multipart/alternative;
	boundary="********************"
Mime-Version: 1.0 (Mac OS X Mail 11.5 \(3445.9.1\))
Subject: ************************
Date: **Mon, 1 Jan 2018 01:04:44 +0100**

```

**Comment by jstanden** [comment]
This is a difficult thing to correct, because it's desirable and permissible to import messages with old dates. For instance, you could hook up a POP3/IMAP mailbox with a 20 year email history and sync it into Cerb. We use the original timestamps to put things in order.

You could use a bot to sanitize/rewrite date headers on inbound mail, but it's probably not worth the effort.
