### ISSUE TITLE
Loosen insert restrictions in API on null/blank strings

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1295]
Perhaps not the best title, but I'm trying for something generic here.  More details in the linked ticket, but the gist is:

> I am running into a bug where contacts are getting created/upserted with
> missing fields like first_name. Looks like this started recently. We're on
> 9.5.4.

...
I suspect the null title is the issue. That should be wrapped in a 'not empty' like the first/last names.
I can also see about making the API more forgiving where it just converts the null to a blank string.

**Comment by jstanden** [comment]
Our validation allows null or strings on those text fields like `contact.title`. However, a null isn't type cast to an empty string like it should be.

The null is being passed through all the way to SQL, where MySQL/MariaDB (in strict mode) return an error rather than completing the UPDATE.

`contact.title` has been a 'not null' field since introduced in 7.1 (Dec 2015).

So I suspect the issue is MySQL/MariaDB changing from non-strict to strict (`sql_mode`), perhaps in an upgrade, and then strictly rejecting the nulls.

We still need to be smarter there and either ignore nulls in a string field, or typecast that to an empty string. We shouldn't be letting this get all the way to SQL as-is.

**Comment by jstanden** [comment]
This is in progress in 9.6-dev
