### ISSUE TITLE
Can't access message headers which contains a minus in the name

### ISSUE THREAD

**Issue by beatbesmer** [jstanden/cerb#1323]
We need to read the message-headers by the "filter incoming mail" behavior. It looks like all headers with an minus in the name, can't be accessed with build 2020060401

PHP Code used for the creation of the header:
~~~
"test-with-minus: 9w4jwef98jimwefsdfik" . "\r\n" .
"testwithoutminus: asdfasdfsadfsf" . "\r\n" .
"mm-beacon: asdasdfdsffasdfsadfsf" . "\r\n" .
"mmbeacon: asd2345asdfdsffasdfsadfsf" . "\r\n" .
~~~

I can see them in CERB (ticket -> message -> show header):
~~~
test-with-minus: 9w4jwef98jimwefsdfik
testwithoutminus: asdfasdfsadfsf
mm-beacon: asdasdfdsffasdfsadfsf
mmbeacon: asd2345asdfdsffasdfsadfsf
~~~

I can also see them in the behavior as an array by using {{headers|json_encode|json_pretty}}:
~~~
"test-with-minus": "9w4jwef98jimwefsdfik",
"testwithoutminus": "asdfasdfsadfsf",
"mm-beacon": "asdasdfdsffasdfsadfsf",
"mmbeacon": "asd2345asdfdsffasdfsadfsf",
~~~

I can only read values, where it's key doesn't contain a minus "-". 
the **action**:
~~~
test-with-minus {{headers.test-with-minus}}
testwithoutminus {{headers.testwithoutminus}}
mmbeacon {{headers.mmbeacon}}
mm-beacon {{headers.mm-beacon}}
~~~

results in the following **output**:
~~~
test-with-minus 0
testwithoutminus asdfasdfsadfsf
mm-beacon asd2345asdfdsffasdfsadfsf
mm-beacon 0
~~~

Replacing the minus in the name by an underscore seems to work. 
This doesn't ocures with minus in the value.

Didn't test it on from other behaviors nor with other "special-characters" in the headers name

**Comment by beatbesmer** [comment]
also met this problem on the "new message added to ticket" behavior.

**Comment by jstanden** [comment]
Hi Beat!

In bot scripting, the minus is ambiguous. It can look like part of the array element name (key), or a mathematical operation. It assumes the latter.

To access an array key with special characters, including minus, use `[]` and string literals rather than dot-notation.

For instance, `{{headers['test-with-minus']}}` will work.

That's the usual way of accessing array elements by key. The dot syntax is a shortcut for fairly simple keys.
