### ISSUE TITLE
Provide a more helpful error when logging in with a bad CSRF token

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1375]
When a worker logs out and leaves the login form sitting there, the CSRF token grows stale.  When they try to log back in with a stale token, they get "access denied" as the error, instead of a more helpful result.

**Comment by jweinraub** [comment]
We have been experiencing this too.  Though one user states he can leave a ticket open over the weekend he will come back, do an action which requires reauthentication and gets the same access denied.  Rather than a better message, is there a way to better manage the stale token so the onus isn't on the user?

**Comment by jstanden** [comment]
I'll see if we can fit this into the tail end of the 10.4 release.

**Comment by jstanden** [comment]
Fixed in 10.4.
