### ISSUE TITLE
Grammarly extension changes cursor position on replies

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#1436]
The Grammarly browser plugin puts the cursor at the end of the message when replying, rather than where it belongs.

**Comment by jstanden** [comment]
This was an issue with behaviors that modified the reply form, rather than Cerb code.

I changed:

~~~
$textarea_reply.setCursorLocation(0);
~~~

To:

~~~
setTimeout(function() { $textarea_reply.setCursorLocation(0); }, 0);
~~~

This just moves the cursor change into a different thread, which appears to resolve the issue.

In 10.0 this won't be an issue since the draft can be modified before the reply editor opens.
