### ISSUE TITLE
License clarification

### ISSUE THREAD

**Issue by ugintl** [jstanden/cerb#1518]
I am confused about the license. If I install open source version for a client and do not do any modifications then 

- Do I still have to buy license?

- Will there be any restrictions?

On the website I saw the pricing section, which made me confused.

**Comment by jstanden** [comment]
Hi @ugintl!

See: https://cerb.ai/license/

The source code is 100% open. We still ask that our copyright and licensing are respected.

You can install a copy of Cerb with no license and it will work with full functionality for a single seat at no cost.

A license grants additional seats and developer support.

**Comment by ugintl** [comment]
@jstanden What is a seat?

**Comment by jstanden** [comment]
In Cerb, we license by seats instead of agents (workers). Seats determine the maximum number of simultaneous workers, but there is no limit to the number of worker accounts you can set up to share those seats.

For example, if you have 10 total workers divided into a day and night shift of 5 people each, you only need a 5 seat license.

We feel this is more fair because it doesn't penalize an organization for having shifts, part-time workers, volunteers, interns, or temps. You also don't need to maintain extra worker licenses just to preserve the history of people who have left your team.

**Comment by ugintl** [comment]
Can you name few commercial alternatives which are not open source?

**Comment by jstanden** [comment]
Salesforce, Airtable, Asana, Zendesk
