### ISSUE TITLE
Email IP reputation issue with Cloudmark Sender Intelligence

### ISSUE THREAD

**Issue by offerblueprint** [jstanden/cerb#1628]
Please forward to the appropriate person/department...
Cloudmark has listed an IP address that our system uses to send email from.  I have asked Cloudmark to delist it, but they were clear that this IP has had issues in the past and that it is unlikely to be delisted.  Please work with Cloudmark to resolve this issue or please send our email from a different IP address.  This is a very important issue!
Here is the message from Cloudmark:  

Failure Reason: Error: 554 [p3plibsmtp03-07.prod.phx3.secureserver.net](http://p3plibsmtp03-07.prod.phx3.secureserver.net/) CMGW IB103. Connection refused. 52.38.96.198 has a poor reputation on Cloudmark Sender Intelligence (CSI). Please visit http://csi.cloudmark.com/reset-request/?ip=52.38.96.198 to request a delisting. 

Additionally, here is what Cloudmark states when trying to delist the IP address:

![image](https://user-images.githubusercontent.com/101204801/157285475-24f2ff9c-5e1e-4a15-b74e-88b14bde814e.png)
 
Thank you for your time and quick resolution!

MIke

**Comment by jstanden** [comment]
Hi Mike!

We can attempt to contact them. We've controlled those IPs for many years without issues.

You can see here that the IP isn't on any other major RBLs:
https://mxtoolbox.com/SuperTool.aspx?action=blacklist%3a52.38.96.198&run=toolpage

We closely monitor email traffic from Cerb Cloud to prevent abuse. If we had frequent spam reports, Amazon would be issuing us warnings and eventually suspend services. They aren't.

The rDNS record is always going to be `cerb.email` for those IPs:

~~~
; ANSWER SECTION:
cerb.email.		300	IN	A	52.38.96.198
cerb.email.		300	IN	A	52.26.43.179
cerb.email.		300	IN	A	52.37.164.181
cerb.email.		300	IN	A	52.36.74.164
cerb.email.		300	IN	A	54.148.127.4
cerb.email.		300	IN	A	54.70.94.68
cerb.email.		300	IN	A	35.164.164.45
cerb.email.		300	IN	A	52.33.230.88
~~~

It wouldn't make sense for us to personalize the rDNS for thousands of clients. However, they may want `cerb.email` to redirect to our website.

While we look into this, you can use any SMTP service with Cerb Cloud as a backup (Postmark, Sendgrid, Mailgun, Gmail, Office365, etc), or your own.

**Comment by jstanden** [comment]
We can't submit a second delisting request for 24 hours, so I'll pick this back up tomorrow.

**Comment by offerblueprint** [comment]
Thank you!  This just started a few days ago and this is the first time we
have had this problem.  Thank you for your quick response and attention to
this matter.

Mike

**Comment by jstanden** [comment]
We've had occasional issues with Proofpoint over the years. They have their own special alarm in our monitoring, but I don't see any alerts in the past 18mo for that one. They've never provided a single piece of evidence for spam. However, at least once a client had a mail loop from a misconfigured auto-responder (two autoresponders mailed each other back and forth) and that likely led to the listing.

Cloudmark appears to be a separate list. It looks like all of your failed deliveries are just on `52.38.96.198`, so we could temporarily take that IP out of rotation. We've reserved that IP for over 6 years.

All of our active/standby IPs for `cerb.email` have the same rDNS, so we'd have to assume eventually they'll misreport them all. It's odd they're just picking on the one since those deliveries are load balanced.

If it's only a few messages, in the meantime you can also use the 'Send again' feature in Cerb to re-deliver the failed message (it's in the `...` menu below the message). There's a good chance that would go out through one of the other IPs.

**Comment by jstanden** [comment]
We temporarily took `52.38.96.198` out of rotation.

**Comment by offerblueprint** [comment]
Hey Jeff....just got this back from Cloudmark.  All should be good!

Dear Michael Schoenberger,

Thank you for contacting Cloudmark.

I have reset the reputation of your IP, so you should see delivery improve
shortly. Please note that updates do not occur instantly but should
generally happen within an hour of receiving this response.

--
Cloudmark CSI Support

Thanks again for your help!!

Mike

**Comment by jstanden** [comment]
Great news, thanks! :)
