### ISSUE TITLE
[Composing] Organization doesn't stay set when composing a ticket

### ISSUE THREAD

**Issue by Edward-git0** [jstanden/cerb#1669]
When you compose a new ticket in Cerb if you set an organization it does not save. After you create the ticket you have to set the org again by editing the ticket.

![image](https://user-images.githubusercontent.com/54463935/185653353-d9ff5002-e0e8-449c-8412-e4c62c87d12f.png)

**Comment by jstanden** [comment]
Thanks for the report! I'll give this a test and post an update here.

**Comment by jstanden** [comment]
It looks like existing organizations work, but it doesn't create a new organization from compose.

The main purpose of the `Organization:` field on compose is to suggest participants; but we can implement org creation as well since that's expected behavior.

**Comment by Edward-git0** [comment]
Hey Jeff,

Thanks for looking into this! In my experience (and those in my company who
work in Cerb) existing organizations have not been working.

Let me know your thoughts on this please.

**Comment by jstanden** [comment]
I fixed the issue with creating new orgs during compose. We'll deploy that with 10.2.7.

I'm not able to reproduce the issue with linking composed tickets to existing orgs. I'll try with a clean 10.2.6 checkout to make sure the dev branch isn't special.

A quick patch for creating orgs from compose in the meantime is:

```diff
Index: features/cerberusweb.core/api/dao/mail_queue.php
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/features/cerberusweb.core/api/dao/mail_queue.php b/features/cerberusweb.core/api/dao/mail_queue.php
--- a/features/cerberusweb.core/api/dao/mail_queue.php	(revision 0e0ab48757aa6fbb3bc16fdb4dec122ceeab28d0)
+++ b/features/cerberusweb.core/api/dao/mail_queue.php	(date 1661025557126)
@@ -924,7 +924,7 @@
 				$properties['org_id'] = $this->getParam('org_id');
 			
 			if($this->hasParam('org_name'))
-				$properties['org_id'] = DAO_ContactOrg::lookup($this->getParam('org_name'));
+				$properties['org_id'] = DAO_ContactOrg::lookup($this->getParam('org_name'), true);
 			
 			if($this->hasParam('status_id'))
 				$properties['status_id'] = $this->getParam('status_id');
```

Converting a draft to a ticket was only looking up orgs, but not creating on missing ones. The lookup function has an optional argument for handling that.

Is there a chance your org names didn't 100% match an existing org? That should be unlikely since the field autocompletes in the browser.

It's also possible a behavior or automation is replacing the `org_id` field. Some clients have workflows to auto-assign tickets to orgs based on sender domains. The default in something like that could blank out the org field by default.

Are you on a recent 10.2. build?

I'll let you know if I get different results with a clean checkout.

**Comment by jstanden** [comment]
I **can** reproduce your issue with compose not assigning existing orgs in a clean 10.2.6 checkout.

We'll get that fixed up. Thanks again for the report.

**Comment by jstanden** [comment]
Actually, it looks like existing orgs are still being set properly. But default ticket card popups aren't configured to show the organization field. When I click into the ticket profile it still has the org linked.

Can you click 'Edit' in the 'Properties' on a card popup:

![CleanShot 2022-08-20 at 17 52 05@2x](https://user-images.githubusercontent.com/63288/185770902-f537bc2e-36c4-4f21-95d5-1af079f1185a.png)

And verify that the 'Organization' field is enabled to display:

![CleanShot 2022-08-20 at 17 52 56@2x](https://user-images.githubusercontent.com/63288/185770915-15552c94-5dbc-4bd0-b9ed-48988baa0277.png)

Are your organizations also not showing up on ticket profile pages?

**Comment by Edward-git0** [comment]
The organization field is enabled on our ticket profile pages - it just
isn’t being set. We do have an automation that assigns an org based on the
participants if they are linked to one, and based on some testing that
appears to be the case.
