### ISSUE TITLE
Saved search filters from the filter helper don't work

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#336]
So, this is probably a more general problem, but it was noticed in the saved searches area.

Add a new saved search, of type worker.  Click the query area, then click Filters -> Toggle Helper.  Use 'List', 'Administrator', and yes, and say "update filters".  The worker worklist now shows the correct results.  Use the "Save Worklist" button to go back to the new saved search dialog, and it tosses the filters you just added.

**Comment by jstanden** [comment]
The issue here is the 'Toggle Helper' step, which is deprecated and being removed.

The worklist chooser in saved searches doesn't care about the filters on the worklist. It only cares about the quick search query that you construct.  It doesn't attempt to convert the old style filters into quick search syntax.
