### ISSUE TITLE
Contacts should be able to reference multiple email addresses and organizations

### ISSUE THREAD

**Issue by rbaker87** [jstanden/cerb#352]
As it stands, a Contact is essentially just a glorified email address record with added default custom fields. An individual can have multiple email addresses and be associated with multiple organizations. This should work similar to the way that an organization can relate to multiple contacts/email addresses.

**Comment by jstanden** [comment]
You can associate multiple email addresses with a single contact already.  You'd do that from the email address records themselves.  Those will show up on the 'Email Addresses' counter button on the contact card.

On the contact record you select a 'primary' email address, because we need something to default to when doing broadcasts, sending mail from bots, etc.

Contacts currently map 1:1 with organizations, although you're welcome to use record links to add additional relationships.  If the same individual is in multiple organizations, we recommend creating a new contact record per organization.  Otherwise it's difficult for bots to determine in which capacity someone is acting during a given interaction.
