### ISSUE TITLE
Bulk Attachment Deletion

### ISSUE THREAD

**Issue by iammattmartin** [jstanden/cerb#417]
In older versions of Cerb, there was an ability to bulk delete attachments from a list although that option isn't to be found now.

This would be helpful for tickets that have since been deleting leaving their attachments behind. Although would have expected attachments to go too when only linked to that ticket but that's another matter.

**Comment by jstanden** [comment]
Hey @mattmartincouk!

Yeah, when we changed attachments worklists the bulk delete feature needed to be reimplemented. Now that we have itemized permissions in 8.1 it'll be easier to redo this.  We've had to field a few support requests where we restore attachments from backups after someone deleted them accidentally.

Previously, attachment worklists were based on the "links" between attachments and records, so the same underlying file could appear multiple times. That was changed so that the attachments worklist shows the files themselves, and the links are displayed on cards. This makes functionality like choosers and behavior variables work as you would expect.

As for attachments being cleaned up, maintenance will remove files that have no records linked to them if they are more than 24 hours old. That cool-down period allows a bot/worker to create a file without immediately using it (it's also how worklist exports create their files, and how they're cleaned up).

Your maintenance scheduler job may run nightly/weekly, depending on your configuration. You can check from **Setup -> Configure -> Scheduler -> Maintenance**.

Do you have any orphaned attachments that are being left around longer than the maintenance?  Is it possible your maintenance job is disabled?

**Comment by jstanden** [comment]
Related to #175, #363

**Comment by iammattmartin** [comment]
Ah ha.

The main reason was that stuff was being left behind and during testing, we changed the maint job to 1 hour. Stuff goes but things are left behind.

One thing that was useful in older versions was to delete attachments you really didn't need any more en-masse but now we'd have to go through them one by one which could (would) get quite tedious.

**Comment by jstanden** [comment]
Implemented in 8.3.6
