### ISSUE TITLE
[Bots] On 'before sending worker message' behaviors, ticket-based snippets don't have values on a compose

### ISSUE THREAD

**Issue by jstanden** [jstanden/cerb#467]
They work on a reply.

**Comment by jstanden** [comment]
@mattmartincouk via https://twitter.com/mattmartincouk/status/918920913906733056

**Comment by jstanden** [comment]
To solve this we'd need to change a bit more logic than I'd prefer to do in a maintenance update.

We'd need to generate basic ticket details before the message exists.  It'll always be a bit chicken/egg when composing from the 'before sending' events, because the message doesn't exist until the email is sent (by design).  If the message fails we just make a draft rather than a ticket/message.

For this particular use case, the group fields could be pulled from a different placeholder, based on the form rather than the future ticket.

**Comment by iammattmartin** [comment]
To expand the use case a little as via the interface is only on testing. When we come to push this live, it will likely be solely from the API so that could introduce its own challenge. 

Although, we already know the group ID and various bits so if we can pass that over to call the data before the send that would solve the problem in the short term as the desired outcome at least would be achieved

**Comment by jstanden** [comment]
Yeah, that makes sense.

In the above commit I tweaked **Before message sent from worker** events so that **Group** is a valid target (with or without a ticket existing yet). That way you can use a group snippet to do the signature based on group custom fields like your example.

That should also automatically work with the API too.
