### ISSUE TITLE
ldap plugin requires Customer authentication part to be filled in

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#506]
We recently re-enabled the ldap plugin and it seems to require that we fill in the "Customer authentication" part even though we have no customers that can log in.

Seems something that can be optional.

Version 7.2.5 (Build 2017010201)

**Comment by jstanden** [comment]
I believe this hasn't been an issue since the introduction of [connected accounts in 7.3](https://cerb.ai/releases/7.3/#connected-accounts) back in Feb. 

At that point, we split up worker and portal use of LDAP to connected accounts. Each portal can use a different LDAP backend.

For workers:
<img width="676" alt="upload" src="https://user-images.githubusercontent.com/63288/32247376-5a436b6a-be3f-11e7-8da5-e29683ef7b46.png">

For portals:
<img width="463" alt="upload2" src="https://user-images.githubusercontent.com/63288/32247378-5a58c712-be3f-11e7-99d1-70c992e22896.png">
