### ISSUE TITLE
[scheduler/cron] be more informative about scheduling issues via a notification to admins

### ISSUE THREAD

**Issue by nbeernink** [jstanden/cerb#509]
It would be nice as an admin to be more informed about issues with cerb's cronjobs.

We had a networking issue that slowed down downloading mailboxes and it was delayed quite a bit.

If the cron is set to fetch messages every minute and it's taking longer than that, show a notification about it (similar to failing to download) instead of having to wait for vague user suspicions and finding the problem that way.

Same goes for all the other cron jobs. If they fail to miss the schedule, notify the admins.

**Comment by jstanden** [comment]
Yeah, standard cronjobs are a bit limited there.

In Cerb Cloud, we use [Cronfire](https://github.com/wgm/cronfire) which logs the full output from all the worker processes. We use Amazon Cloudwatch/Lambda alerts to report on the logs.  Cronfire uses Redis, so we also monitor metrics there (queue length, last runtime, etc).

I've been meaning to post a guide on using Cronfire instead of crontab.

**Comment by nbeernink** [comment]
Would it not be possible to include this as a feature in cerb?

In order to switch to an alternative to crontab a guide would be useful.

**Comment by jstanden** [comment]
This would be trivial to do with automation events now.

**Comment by jstanden** [comment]
The scheduler dates are also reported in `/debug/status` now for monitoring.
