### ISSUE TITLE
Creating and downloading an attachment using abstract records

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#529]
Using the records endpoint for attachment I can retrieve an attachment, but how do we get the content and create an attachment with content?

**Comment by jstanden** [comment]
At the moment, you can still use the `/attachments` module to download:
https://cerb.ai/docs/api/modules/attachments/#download

We're looking at a way to abstractly handle those non-CRUD actions in the `/records` API.  That's why few of the older API modules aren't marked deprecated yet (e.g. downloading raw attachments, running bot behaviors, adding members to groups).

As for creating an attachment with content, I'll update the examples on its docs page and post the link here in a few mins.

**Comment by jstanden** [comment]
Here you go:

* https://cerb.ai/docs/api/records/attachment/#create-an-attachment-with-plaintext-content
* https://cerb.ai/docs/api/records/attachment/#create-an-attachment-with-binary-content
