### ISSUE TITLE
Publically Editable Bot/Bot Actions [feature-request]

### ISSUE THREAD

**Issue by DavidAllewell** [jstanden/cerb#828]
A use-case for setting different permissions on various bot processes has arisen in my workflow, with the idea of bots being able to automatically comment on tasks/records based on information it can see.

Obviously, if not all the information it needs is provided, then there'll be bits missing in the bot's comment. I'd like to be able to set different permissions for different bot actions, allowing different user groups to access/edit these comments.

I.e., set a public permission on a comment being made on a new task, but set private permissions on a comment made on a ticket.

**Comment by jstanden** [comment]
Hi David! This is actually something on our near-term roadmap.

In the upcoming 9.1 release we've added connected services to further organize connected accounts. This enables arbitrary service providers to be created using OAuth1/OAuth2/SAML/OpenID-Connect/HTTP-Basic/etc. We'll also be supporting OAuth2 authentication in our API.

With OAuth2/OIDC specifically, the concept of API "scopes" overlaps with our role-based permissions.

The move toward OAuth2 also allows auth flows like 'client credentials', as well as bearer tokens generated in the UI.

Our plan is that those other auth flows could be used with a bot as the primary API actor, rather than a worker. That would solve the issue right now where integrations using the API have to assume the role of a worker (and people resort to adding a dummy worker account for the bot).

To do that properly, we'll need to expand roles to bots as well. That's something I'm planning to start working on for 9.2 as soon as we ship 9.1 (later this month).

In 9.2, we're also planning to work on 'modular community portals', which will allow arbitrary authentication (social media profiles, SAML/OIDC directories, etc). That means the authenticated user won't always be a 'contact' record; and they could even be represented as a custom record. We'll need a way to determine what those abstract users are able to see and do, and we'll likely expand roles to cover that as well.

After that roles refactor, we'd ideally end up with a cleaner system where roles could be applied directly to several 'actor' oriented record types (workers, bots, contacts, etc).

Finally, that would lead us to a cleaner way to use roles to delegate read/write privileges on arbitrary records like comments, snippets, behaviors, profile tabs, dashboard widgets, etc.

I'll keep this issue open in 9.2 as a reminder to give you some progress updates.

**Comment by jstanden** [comment]
This should be possible with the role refactor as of 9.2.
