### ISSUE TITLE
Separate sigs between Compose / Reply; add ticket tokens to Reply sigs

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#875]
The specific use-case is a request for inserting the ticket mask in the sig of a reply, but because sigs are inserted on a Compose prior to the ticket existing, we haven't been able to use ticket tokens there.

**Comment by kiranos** [comment]
Yes we're thinking about removing mask from subject, but would still want the MASK referensed somewhere in the ticket body. So a field in the signature would be good imo.

Its so clients can easily lookup ticket id and tell us about it.

**Comment by jstanden** [comment]
I like the idea of optionally splitting up the signature template into compose/reply variations, rather than requiring people to check if every placeholder is not null first. We have another related issue (#493) for HTML variants in signatures as well. Issue #503 attempts to address the same need using placeholders.

Another related issue (#494) for attachments on sigs for logos and such.

**Comment by jstanden** [comment]
This could be done with a compose/reply editor interaction toolbar now.
