### ISSUE TITLE
Allow inclusion of other snippets inside snippets

### ISSUE THREAD

**Issue by Hildy** [jstanden/cerb#936]
A customer has requested (in order to only have to maintain one copy of a price list) the ability to include snippets within other snippets.  A snippet would be able to include the content of another snippet of it's own type, or of a plain-text snippet.

**Comment by jstanden** [comment]
I think with our recent pattern, we'd just add a globally unique URI to snippets as an alias. Then an alias could `#include <snippet-uri>`, as long as what's referenced is the same type or plaintext (as you said).

That should be pretty easy to do, because we'd really just preprocess for the #include tags and grab the literal snippet content (sharing placeholders) to replace those with a `preg_replace_callback()`. Then do the snippet dictionary stuff once

**Comment by jstanden** [comment]
This should just be done with interactions on the compose/reply editor now.
