### ISSUE TITLE
show_meta on records API, no longer shows meta

### ISSUE THREAD

**Issue by mrlilly** [jstanden/cerb#943]
When using:
/rest/records/ticket/123.json?show_meta=1
it no longer brings back the meta data (_labels or _types).

It still shows when doing /rest/tickets/123.json?show_meta=1

**Comment by jstanden** [comment]
This is related to a few early release 9.2.4 patches for API performance. Searches intentionally don't include meta for each result; as the plan there is to return it once for the entire set. The types/labels would be identical for each dictionary.

I'll take a look.

**Comment by jstanden** [comment]
Fixed in 9.3

**Comment by mrlilly** [comment]
Thanks for putting it back, but!
On the older end points 'tickets', 'groups' etc you return the meta keys as _types and _labels directly off the root. Now you have added the meta back to records you have added the keys types and labels nested inside the _meta key? Can this be put back how it was originally, rather than having to look for different keys for different responses?

**Comment by jstanden** [comment]
Hey there! We're phasing out the deprecated endpoints like `/tickets`. You should use `/records` for all creating, updating, searching, etc.

The main reason for changing how `show_meta` works is that it was very inefficient to return that information for every result in a search as part of their dictionary. Those operations no longer even consider the meta. With the flag in the recent version, we add it to the response as a second step. Because it couldn't be part of the individual results within a search, it's in a new key at the root of the response. To be consistent going forward (rather than with the deprecated past), the record retrieval behaves the same way.
